### ISSUE TITLE
Add Auth Theme Using Netlify Identity

### ISSUE THREAD

**Issue by TrevHeath** [Novvum/novvum#26]
**Is your feature request related to a problem? Please describe.**
Currently there is no auth mechanism available to the novvum suite of applications.  Specifically Whills where company sensitive content is located.  This means anyone can view the content and Google can index it.

Down the road, auth may be valuable to the novvum website or an audit client as well.

**Describe the solution you'd like**
I would like to implement the Netlify auth service as a theme in the `novvum` repo.  This would provide easy access to an authentication mechanism through the suite of novvum web applications.

It would include -
- Netlify widget
- `auth.js` file which would handle the appropriate token storage and manipulation.  As well as utility functions for interacting with the user metainformation or roles.

How to authorize access to content
- Utilizing the role feature in netlify we will be able to tag users and authorize specific content.

For example: A user with the `Novvum Team` tag can access all whills pages and audit reports.  However, a `client` may only be able to access specific client pages like an audit.

**Describe alternatives you've considered**
No simple logical alternatives as this is a time-sensitive ticket.

**Additional context**

**Comment by TrevHeath** [comment]
@rohit-ravikoti I would like to make the auth available to all clients in the novvum repo.  Which theme do you think it makes sense to utilize?  or should I implement a micro theme just for auth?

**Comment by rohit-ravikoti** [comment]
Great idea! Let's go for it!

**Comment by rohit-ravikoti** [comment]
Let's call it @novvum/gataby-theme-auth
